import MoreVertIcon from "@mui/icons-material/MoreVert";
export const Data1 = [
  {
    ID: "1",
    Clientname: "J.K Patel",
    Contact: "+91 8832832382",
    Firmname: "Radhe Trades",
    Orders: "5",
    dots: <MoreVertIcon />,
  },
  {
    ID: 2,
    Clientname: "Rajesh Patel",
    Contact: "+91 8832832382",
    Firmname: "Radhe Trades",
    Orders: "1",
    dots: <MoreVertIcon />,
  },
  {
    ID: 3,
    Clientname: "David John",
    Contact: "+91 8832832382",
    Firmname: "Radhe Trades",
    Orders: "3",
    dots: <MoreVertIcon />,
  },
  {
    ID: 4,
    Clientname: "Jackey Patel",
    Contact: "+91 8832832382",
    Firmname: "Radhe Trades",
    Orders: "2",
    dots: <MoreVertIcon />,
  },
  {
    ID: 5,
    Clientname: "Hareshbhai Patel",
    Contact: "+91 8832832382",
    Firmname: "Radhe Trades",
    Orders: "5",
    dots: <MoreVertIcon />,
  },
  {
    ID: 6,
    Clientname: "Ronak patel",
    Contact: "+91 8832832382",
    Firmname: "Radhe Trades",
    Orders: "7",
    dots: <MoreVertIcon />,
  },
  {
    ID: 7,
    Clientname: "Roshan Patel",
    Contact: "+91 8832832382",
    Firmname: "Radhe Trades",
    Orders: "5",
    dots: <MoreVertIcon />,
  },
  {
    ID: 8,
    Clientname: "Jayesh Gohel",
    Contact: "+91 8832832382",
    Firmname: "Radhe Trades",
    Orders: "8",
    dots: <MoreVertIcon />,
  },
];
