import MoreVertIcon from "@mui/icons-material/MoreVert";
export const Data = [
    {
      ID: "1",
      Income :"Radhe Textile",
      Type  :"Cash",
      Currency  :"USD",
      Amount   :"12000",
      Date  : "19 Nov,2021",
      Account : "Credit",
      dots   : <MoreVertIcon />,
    },
    {
      ID: "2",
      Income :"Radhe Textile",
      Type  :"Cash",
      Currency  :"USD",
      Amount   :"21,000",
      Date  : "19 Nov,2021",
      Account : "Credit",
      dots   : <MoreVertIcon />,
    },
    {
      ID: "3",
      Income :"Radhe Textile",
      Type  :"Bank",
      Currency  :"USD",
      Amount   :"22,10,000",
      Date  : "19 Nov,2021",
      Account : "Credit",
      dots   : <MoreVertIcon />,
    },
    {
      ID: "4",
      Income :"Radhe Textile",
      Type  :"Bank",
      Currency  :"USD",
      Amount   :"10,000",
      Date  : "19 Nov,2021",
      Account : "Credit",
      dots   : <MoreVertIcon />,
    },
    {
      ID: "5",
      Income :"Radhe Textile",
      Type  :"Cash",
      Currency  :"USD",
      Amount   :"12000",
      Date  : "19 Nov,2021",
      Account : "Credit",
      dots   : <MoreVertIcon />,
    },
    {
      ID: "6",
      Income :"Radhe Textile",
      Type  :"Cash",
      Currency  :"USD",
      Amount   :"1,2000",
      Date  : "19 Nov,2021",
      Account : "Credit",
      dots   : <MoreVertIcon />,
    },
    {
      ID: "7",
      Income :"Radhe Textile",
      Type  :"Cash",
      Currency  :"USD",
      Amount   :"80,000",
      Date  : "19 Nov,2021",
      Account : "Credit",
      dots   : <MoreVertIcon />,
    },
    {
      ID: "8",
      Income :"Radhe Textile",
      Type  :"Cash",
      Currency  :"USD",
      Amount   :"12,000",
      Date  : "19 Nov,2021",
      Account : "Credit",
      dots   : <MoreVertIcon />,
    },
  ]
